name: docs_montecarlo
#channels:

 # - defaults
#dependencies:
    # Base depends
 # - python
  #- pip
  



    # Pip-only installs
 # - pip:
  #  - -e ../

#name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - numpy
  - matplotlib

    # Pip-only installs
  - pip:
        - sphinx-rtd-theme
